import { Manrope, Covered_By_Your_Grace, Rubik } from "next/font/google";
import "./globals.css";

const manrope = Manrope({ subsets: ["latin"] });
const covered = Covered_By_Your_Grace({
  subsets: ["latin"],
  variable: "--font-covered",
  weight: ["400"]
})
const rubik = Rubik({ 
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: [ "400", "500", "600"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className} ${covered.variable} ${rubik.variable}`}>{children}</body>
    </html>
  );
}
